# @package _global_
defaults:
  - override /dataset: horm

dataset:
  sample_ids:
    - 17304

kohn_sham:
  basis: "6-31G(2df,p)"
  xc: "PBE"
  initialization: "minao"
  grid_level: 3
  prune_method: "nwchem_prune"
  density_fit_basis: "def2-universal-jfit"
  density_fit_threshold: 30
  convergence_tolerance: 1e-9
  compute_forces: false
  compute_hessian: false

density_fitting_method: "hartree+external_mofdft"
of_basis_set: "even_tempered_2.5"

n_molecules: 1
start_idx: 0
num_processes: 1
num_threads_per_process: 1
max_memory_per_process: 4000
log_level: INFO

hydra:
  run:
    dir: /mnt/afs/home/xiazhenhao/dft/logs/horm_pbe_labels/${now:%Y-%m-%d}_${now:%H-%M-%S}
  sweep:
    dir: /mnt/afs/home/xiazhenhao/dft/logs/horm_pbe_labels_multirun/${now:%Y-%m-%d}_${now:%H-%M-%S}
