_target_: mldft.ml.models.components.loss_function.WeightedLoss
energy_loss:
  weight: 0.1
  loss:
    _target_: mldft.ml.models.components.loss_function.EnergyLoss
    loss_function:
      _target_: torch.nn.L1Loss
      reduction: none
    sample_weigher:
      _target_: mldft.ml.models.components.sample_weighers.HasEnergyLabelSampleWeigher

gradient_loss:
  weight: 0.8
  loss:
    _target_: mldft.ml.models.components.loss_function.EnergyGradientLoss
    loss_function:
      _target_: torch.nn.L1Loss
      reduction: none
    sample_weigher:
      _target_: mldft.ml.models.components.sample_weighers.HasEnergyLabelSampleWeigher

force_loss:
  weight: 1.0
  loss:
    _target_: mldft.ml.models.components.loss_function.ForceLoss
    loss_function:
      _target_: torch.nn.L1Loss
      reduction: none
    sample_weigher:
      _target_: mldft.ml.models.components.sample_weighers.HasEnergyLabelSampleWeigher

energy_secant_loss:
  weight: 0.01
  loss:
    _target_: mldft.ml.models.components.loss_function.PairEnergySecantLoss
    strict_pairs: true
    loss_function:
      _target_: torch.nn.L1Loss
      reduction: none

coefficient_loss:
  weight: 0
  loss:
    _target_: mldft.ml.models.components.loss_function.CoefficientLoss
    loss_function:
      _target_: torch.nn.L1Loss
      reduction: none
    sample_weigher: null
